### ISSUE TITLE
Bada 3.15 files - what to download?

### ISSUE THREAD

**Issue by kovar-ursa** [HKUST-OCTAD-LAB/AirTrafficSim#53]
The instructions and documentation tell the user to download and unzip the Bada 3.15 files.

In the EuroControl site there are over 160 files associated with my Bada 3 license. It is unclear which file(s) need to be downloaded and unzipped.

I believe the base file is:  Release Files | 3.15 | 24 June 2019 | 1.39 MB

But then there are monthly files for every month since June 2019. Do all of those need to be downloaded and installed as well?

**Comment by kyfrankie** [comment]
Hi, thanks for the questions. Please use the data files in the bada_315_cfc  folder which should contain the .APF, .PTD, .PTF data for different aircraft. I believe the monthly update folders only contain the SYNONYM.NEW file.

**Comment by kovar-ursa** [comment]
Thank you!

-David

**Comment by hupei243** [comment]
Hello, how do you check the related files associated with your Bada 3 license? I just got my bada 3.16 license and I wonder where the bada_316_cfc folder is...

**Comment by koujiangheng** [comment]
> The instructions and documentation tell the user to download and unzip the Bada 3.15 files.
> 
> In the EuroControl site there are over 160 files associated with my Bada 3 license. It is unclear which file(s) need to be downloaded and unzipped.
> 
> I believe the base file is: Release Files | 3.15 | 24 June 2019 | 1.39 MB
> 
> But then there are monthly files for every month since June 2019. Do all of those need to be downloaded and installed as well?

Would you mind share bada files? I do not know where to get it.
